site_name: Godot Coreblocks

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Engine Classes: 
    - Objects:
      - Part: classes/objects/Part.md
      - Behavior: classes/objects/Behavior.md
      - ServerBehavior: classes/objects/ServerBehavior.md
      - ClientBehavior: classes/objects/ClientBehavior.md
      - BehaviorFolder: classes/objects/BehaviorFolder.md
      - Player: classes/objects/Player.md
      - Character: classes/objects/Character.md
      - SingletonBehavior: classes/objects/SingletonBehavior.md
      - Image3D: classes/objects/Image3D.md
      - ShaderRect: classes/objects/ShaderRect.md
      - MouseModeBinding: classes/objects/MouseModeBinding.md
      - MultiplayerRemote: classes/objects/MultiplayerRemote.md
      - Sunlight: classes/objects/Sunlight.md
      - SurfaceGui: classes/objects/SurfaceGui.md
      - Trigger3D: classes/objects/Trigger3D.md
      - UDim2: classes/objects/UDim2.md
      - UDim2Anchor: classes/objects/UDim2Anchor.md

    - Systems:
      - Game: classes/singletons/Game.md
      - Workspace: classes/singletons/Workspace.md
      - Players: classes/singletons/Players.md
      - Client: classes/singletons/Client.md
      - Server: classes/singletons/Server.md
      - Chat: classes/singletons/Chat.md
      - Mouse: classes/singletons/Mouse.md
      - Screen: classes/singletons/Screen.md
      - GuiSystem: classes/singletons/GuiSystem.md
      - AudioSystem: classes/singletons/AudioSystem.md
      - LightingSystem: classes/singletons/LightingSystem.md
      - ModSystem: classes/singletons/ModSystem.md
      - CameraSystem: classes/singletons/CameraSystem.md
      - MapSystem: classes/singletons/MapSystem.md
      - ShaderSystem: classes/singletons/ShaderSystem.md
      - ClientScriptSystem: classes/singletons/ClientScriptSystem.md
      - ServerScriptSystem: classes/singletons/ServerScriptSystem.md
      - Replicator: classes/singletons/Replicator.md
      - CoreGui: classes/singletons/CoreGui.md
      - Singleton: classes/singletons/Singleton.md
      - Singleton3D: classes/singletons/Singleton3D.md
      - SingletonCanvas: classes/singletons/SingletonCanvas.md
      - SingletonControl: classes/singletons/SingletonControl.md
      - IBaseSingleton: classes/singletons/IBaseSingleton.md

    - Enums:
      - PriorityChannel: enums/PriorityChannel.md

    - Libraries:
      - Task: classes/libs/TaskLib.md
      - Json: classes/libs/JsonLib.md
      - Ext: classes/libs/Ext.md
      - File: classes/libs/FileLib.md
      - Core: classes/libs/Core.md

    - Attributes:
      - OnClient: classes/attributes/OnClient.md
      - OnServer: classes/attributes/OnServer.md
      - Prerunner: classes/attributes/Prerunner.md

# these are basically just the properties in a md file
exclude_docs: |
  /types
  /helper

theme: 
  name: material
  color_mode: dark
  palette:
    scheme: slate
  locale: en
  highlightjs: true
  hljs_languages:
    - cs
    - csharp

plugins:
  - include-markdown

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences